### ISSUE TITLE
Requirements.txt is suggested

### ISSUE THREAD

**Issue by sergzach** [mathbunnyru/python-cpp-extension#27]
requirements.txt

```
Cython~=3.0.0
pytest~=8.3.0
pytest-benchmark~=4.0.0
```

**Comment by mathbunnyru** [comment]
May I ask you to create a PR, please?

**Comment by sergzach** [comment]
> May I ask you to create a PR, please?

https://github.com/mathbunnyru/python-cpp-extension/pull/28
